/*
Permify API

Permify is an open source authorization service for creating fine-grained and scalable authorization systems.

API version: v0.10.1
Contact: hello@permify.co
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package permify

import (
	"encoding/json"
)

// checks if the SchemaReadResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SchemaReadResponse{}

// SchemaReadResponse SchemaReadResponse is the response message for the Read method in the Schema service. It returns the requested schema.
type SchemaReadResponse struct {
	Schema *SchemaDefinition `json:"schema,omitempty"`
}

// NewSchemaReadResponse instantiates a new SchemaReadResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSchemaReadResponse() *SchemaReadResponse {
	this := SchemaReadResponse{}
	return &this
}

// NewSchemaReadResponseWithDefaults instantiates a new SchemaReadResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSchemaReadResponseWithDefaults() *SchemaReadResponse {
	this := SchemaReadResponse{}
	return &this
}

// GetSchema returns the Schema field value if set, zero value otherwise.
func (o *SchemaReadResponse) GetSchema() SchemaDefinition {
	if o == nil || IsNil(o.Schema) {
		var ret SchemaDefinition
		return ret
	}
	return *o.Schema
}

// GetSchemaOk returns a tuple with the Schema field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SchemaReadResponse) GetSchemaOk() (*SchemaDefinition, bool) {
	if o == nil || IsNil(o.Schema) {
		return nil, false
	}
	return o.Schema, true
}

// HasSchema returns a boolean if a field has been set.
func (o *SchemaReadResponse) HasSchema() bool {
	if o != nil && !IsNil(o.Schema) {
		return true
	}

	return false
}

// SetSchema gets a reference to the given SchemaDefinition and assigns it to the Schema field.
func (o *SchemaReadResponse) SetSchema(v SchemaDefinition) {
	o.Schema = &v
}

func (o SchemaReadResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SchemaReadResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Schema) {
		toSerialize["schema"] = o.Schema
	}
	return toSerialize, nil
}

type NullableSchemaReadResponse struct {
	value *SchemaReadResponse
	isSet bool
}

func (v NullableSchemaReadResponse) Get() *SchemaReadResponse {
	return v.value
}

func (v *NullableSchemaReadResponse) Set(val *SchemaReadResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSchemaReadResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSchemaReadResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSchemaReadResponse(val *SchemaReadResponse) *NullableSchemaReadResponse {
	return &NullableSchemaReadResponse{value: val, isSet: true}
}

func (v NullableSchemaReadResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSchemaReadResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


