/*
Permify API

Permify is an open source authorization service for creating fine-grained and scalable authorization systems.

API version: v0.10.1
Contact: hello@permify.co
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package permify

import (
	"encoding/json"
)

// checks if the Ident type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Ident{}

// Ident An identifier expression. e.g. `request`.
type Ident struct {
	// Required. Holds a single, unqualified identifier, possibly preceded by a '.'.  Qualified names are represented by the [Expr.Select][google.api.expr.v1alpha1.Expr.Select] expression.
	Name *string `json:"name,omitempty"`
}

// NewIdent instantiates a new Ident object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIdent() *Ident {
	this := Ident{}
	return &this
}

// NewIdentWithDefaults instantiates a new Ident object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIdentWithDefaults() *Ident {
	this := Ident{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *Ident) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Ident) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *Ident) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *Ident) SetName(v string) {
	o.Name = &v
}

func (o Ident) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Ident) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return toSerialize, nil
}

type NullableIdent struct {
	value *Ident
	isSet bool
}

func (v NullableIdent) Get() *Ident {
	return v.value
}

func (v *NullableIdent) Set(val *Ident) {
	v.value = val
	v.isSet = true
}

func (v NullableIdent) IsSet() bool {
	return v.isSet
}

func (v *NullableIdent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIdent(val *Ident) *NullableIdent {
	return &NullableIdent{value: val, isSet: true}
}

func (v NullableIdent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIdent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


