/*
Permify API

Permify is an open source authorization service for creating fine-grained and scalable authorization systems.

API version: v0.10.1
Contact: hello@permify.co
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package permify

import (
	"encoding/json"
)

// checks if the BundleWriteResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BundleWriteResponse{}

// BundleWriteResponse BundleWriteResponse is the response for a BundleWriteRequest. It includes a name which could be used as an identifier or acknowledgment.
type BundleWriteResponse struct {
	// Identifier or acknowledgment of the written bundle.
	Names []string `json:"names,omitempty"`
}

// NewBundleWriteResponse instantiates a new BundleWriteResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBundleWriteResponse() *BundleWriteResponse {
	this := BundleWriteResponse{}
	return &this
}

// NewBundleWriteResponseWithDefaults instantiates a new BundleWriteResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBundleWriteResponseWithDefaults() *BundleWriteResponse {
	this := BundleWriteResponse{}
	return &this
}

// GetNames returns the Names field value if set, zero value otherwise.
func (o *BundleWriteResponse) GetNames() []string {
	if o == nil || IsNil(o.Names) {
		var ret []string
		return ret
	}
	return o.Names
}

// GetNamesOk returns a tuple with the Names field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BundleWriteResponse) GetNamesOk() ([]string, bool) {
	if o == nil || IsNil(o.Names) {
		return nil, false
	}
	return o.Names, true
}

// HasNames returns a boolean if a field has been set.
func (o *BundleWriteResponse) HasNames() bool {
	if o != nil && !IsNil(o.Names) {
		return true
	}

	return false
}

// SetNames gets a reference to the given []string and assigns it to the Names field.
func (o *BundleWriteResponse) SetNames(v []string) {
	o.Names = v
}

func (o BundleWriteResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BundleWriteResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Names) {
		toSerialize["names"] = o.Names
	}
	return toSerialize, nil
}

type NullableBundleWriteResponse struct {
	value *BundleWriteResponse
	isSet bool
}

func (v NullableBundleWriteResponse) Get() *BundleWriteResponse {
	return v.value
}

func (v *NullableBundleWriteResponse) Set(val *BundleWriteResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableBundleWriteResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableBundleWriteResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBundleWriteResponse(val *BundleWriteResponse) *NullableBundleWriteResponse {
	return &NullableBundleWriteResponse{value: val, isSet: true}
}

func (v NullableBundleWriteResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBundleWriteResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


