/*
Permify API

Permify is an open source authorization service for creating fine-grained and scalable authorization systems.

API version: v0.10.1
Contact: hello@permify.co
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package permify

import (
	"encoding/json"
)

// checks if the ComputedUserSet type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ComputedUserSet{}

// ComputedUserSet ComputedUserSet defines a set of computed users which includes the relation name.
type ComputedUserSet struct {
	Relation *string `json:"relation,omitempty"`
}

// NewComputedUserSet instantiates a new ComputedUserSet object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComputedUserSet() *ComputedUserSet {
	this := ComputedUserSet{}
	return &this
}

// NewComputedUserSetWithDefaults instantiates a new ComputedUserSet object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComputedUserSetWithDefaults() *ComputedUserSet {
	this := ComputedUserSet{}
	return &this
}

// GetRelation returns the Relation field value if set, zero value otherwise.
func (o *ComputedUserSet) GetRelation() string {
	if o == nil || IsNil(o.Relation) {
		var ret string
		return ret
	}
	return *o.Relation
}

// GetRelationOk returns a tuple with the Relation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComputedUserSet) GetRelationOk() (*string, bool) {
	if o == nil || IsNil(o.Relation) {
		return nil, false
	}
	return o.Relation, true
}

// HasRelation returns a boolean if a field has been set.
func (o *ComputedUserSet) HasRelation() bool {
	if o != nil && !IsNil(o.Relation) {
		return true
	}

	return false
}

// SetRelation gets a reference to the given string and assigns it to the Relation field.
func (o *ComputedUserSet) SetRelation(v string) {
	o.Relation = &v
}

func (o ComputedUserSet) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ComputedUserSet) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Relation) {
		toSerialize["relation"] = o.Relation
	}
	return toSerialize, nil
}

type NullableComputedUserSet struct {
	value *ComputedUserSet
	isSet bool
}

func (v NullableComputedUserSet) Get() *ComputedUserSet {
	return v.value
}

func (v *NullableComputedUserSet) Set(val *ComputedUserSet) {
	v.value = val
	v.isSet = true
}

func (v NullableComputedUserSet) IsSet() bool {
	return v.isSet
}

func (v *NullableComputedUserSet) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComputedUserSet(val *ComputedUserSet) *NullableComputedUserSet {
	return &NullableComputedUserSet{value: val, isSet: true}
}

func (v NullableComputedUserSet) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComputedUserSet) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


