/*
Permify API

Permify is an open source authorization service for creating fine-grained and scalable authorization systems.

API version: v0.10.1
Contact: hello@permify.co
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package permify

import (
	"encoding/json"
)

// checks if the RelationDefinition type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RelationDefinition{}

// RelationDefinition The RelationDefinition message provides detailed information about a specific relation.
type RelationDefinition struct {
	// The name of the relation, which follows a specific string pattern and has a maximum byte size.
	Name *string `json:"name,omitempty"`
	// A list of references to other relations.
	RelationReferences []RelationReference `json:"relationReferences,omitempty"`
}

// NewRelationDefinition instantiates a new RelationDefinition object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRelationDefinition() *RelationDefinition {
	this := RelationDefinition{}
	return &this
}

// NewRelationDefinitionWithDefaults instantiates a new RelationDefinition object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRelationDefinitionWithDefaults() *RelationDefinition {
	this := RelationDefinition{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *RelationDefinition) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RelationDefinition) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *RelationDefinition) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *RelationDefinition) SetName(v string) {
	o.Name = &v
}

// GetRelationReferences returns the RelationReferences field value if set, zero value otherwise.
func (o *RelationDefinition) GetRelationReferences() []RelationReference {
	if o == nil || IsNil(o.RelationReferences) {
		var ret []RelationReference
		return ret
	}
	return o.RelationReferences
}

// GetRelationReferencesOk returns a tuple with the RelationReferences field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RelationDefinition) GetRelationReferencesOk() ([]RelationReference, bool) {
	if o == nil || IsNil(o.RelationReferences) {
		return nil, false
	}
	return o.RelationReferences, true
}

// HasRelationReferences returns a boolean if a field has been set.
func (o *RelationDefinition) HasRelationReferences() bool {
	if o != nil && !IsNil(o.RelationReferences) {
		return true
	}

	return false
}

// SetRelationReferences gets a reference to the given []RelationReference and assigns it to the RelationReferences field.
func (o *RelationDefinition) SetRelationReferences(v []RelationReference) {
	o.RelationReferences = v
}

func (o RelationDefinition) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RelationDefinition) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.RelationReferences) {
		toSerialize["relationReferences"] = o.RelationReferences
	}
	return toSerialize, nil
}

type NullableRelationDefinition struct {
	value *RelationDefinition
	isSet bool
}

func (v NullableRelationDefinition) Get() *RelationDefinition {
	return v.value
}

func (v *NullableRelationDefinition) Set(val *RelationDefinition) {
	v.value = val
	v.isSet = true
}

func (v NullableRelationDefinition) IsSet() bool {
	return v.isSet
}

func (v *NullableRelationDefinition) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRelationDefinition(val *RelationDefinition) *NullableRelationDefinition {
	return &NullableRelationDefinition{value: val, isSet: true}
}

func (v NullableRelationDefinition) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRelationDefinition) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


