/*
Permify API

Permify is an open source authorization service for creating fine-grained and scalable authorization systems.

API version: v0.10.1
Contact: hello@permify.co
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package permify

import (
	"encoding/json"
)

// checks if the PermissionSubjectPermissionRequestMetadata type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PermissionSubjectPermissionRequestMetadata{}

// PermissionSubjectPermissionRequestMetadata PermissionSubjectPermissionRequestMetadata metadata for the PermissionSubjectPermissionRequest.
type PermissionSubjectPermissionRequestMetadata struct {
	// Version of the schema.
	SchemaVersion *string `json:"schema_version,omitempty"`
	// The snap token to avoid stale cache, see more details on [Snap Tokens](../../operations/snap-tokens).
	SnapToken *string `json:"snap_token,omitempty"`
	// Whether to only check permissions.
	OnlyPermission *bool `json:"only_permission,omitempty"`
	// Query limit when if recursive database queries got in loop.
	Depth *int32 `json:"depth,omitempty"`
}

// NewPermissionSubjectPermissionRequestMetadata instantiates a new PermissionSubjectPermissionRequestMetadata object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPermissionSubjectPermissionRequestMetadata() *PermissionSubjectPermissionRequestMetadata {
	this := PermissionSubjectPermissionRequestMetadata{}
	return &this
}

// NewPermissionSubjectPermissionRequestMetadataWithDefaults instantiates a new PermissionSubjectPermissionRequestMetadata object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPermissionSubjectPermissionRequestMetadataWithDefaults() *PermissionSubjectPermissionRequestMetadata {
	this := PermissionSubjectPermissionRequestMetadata{}
	return &this
}

// GetSchemaVersion returns the SchemaVersion field value if set, zero value otherwise.
func (o *PermissionSubjectPermissionRequestMetadata) GetSchemaVersion() string {
	if o == nil || IsNil(o.SchemaVersion) {
		var ret string
		return ret
	}
	return *o.SchemaVersion
}

// GetSchemaVersionOk returns a tuple with the SchemaVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PermissionSubjectPermissionRequestMetadata) GetSchemaVersionOk() (*string, bool) {
	if o == nil || IsNil(o.SchemaVersion) {
		return nil, false
	}
	return o.SchemaVersion, true
}

// HasSchemaVersion returns a boolean if a field has been set.
func (o *PermissionSubjectPermissionRequestMetadata) HasSchemaVersion() bool {
	if o != nil && !IsNil(o.SchemaVersion) {
		return true
	}

	return false
}

// SetSchemaVersion gets a reference to the given string and assigns it to the SchemaVersion field.
func (o *PermissionSubjectPermissionRequestMetadata) SetSchemaVersion(v string) {
	o.SchemaVersion = &v
}

// GetSnapToken returns the SnapToken field value if set, zero value otherwise.
func (o *PermissionSubjectPermissionRequestMetadata) GetSnapToken() string {
	if o == nil || IsNil(o.SnapToken) {
		var ret string
		return ret
	}
	return *o.SnapToken
}

// GetSnapTokenOk returns a tuple with the SnapToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PermissionSubjectPermissionRequestMetadata) GetSnapTokenOk() (*string, bool) {
	if o == nil || IsNil(o.SnapToken) {
		return nil, false
	}
	return o.SnapToken, true
}

// HasSnapToken returns a boolean if a field has been set.
func (o *PermissionSubjectPermissionRequestMetadata) HasSnapToken() bool {
	if o != nil && !IsNil(o.SnapToken) {
		return true
	}

	return false
}

// SetSnapToken gets a reference to the given string and assigns it to the SnapToken field.
func (o *PermissionSubjectPermissionRequestMetadata) SetSnapToken(v string) {
	o.SnapToken = &v
}

// GetOnlyPermission returns the OnlyPermission field value if set, zero value otherwise.
func (o *PermissionSubjectPermissionRequestMetadata) GetOnlyPermission() bool {
	if o == nil || IsNil(o.OnlyPermission) {
		var ret bool
		return ret
	}
	return *o.OnlyPermission
}

// GetOnlyPermissionOk returns a tuple with the OnlyPermission field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PermissionSubjectPermissionRequestMetadata) GetOnlyPermissionOk() (*bool, bool) {
	if o == nil || IsNil(o.OnlyPermission) {
		return nil, false
	}
	return o.OnlyPermission, true
}

// HasOnlyPermission returns a boolean if a field has been set.
func (o *PermissionSubjectPermissionRequestMetadata) HasOnlyPermission() bool {
	if o != nil && !IsNil(o.OnlyPermission) {
		return true
	}

	return false
}

// SetOnlyPermission gets a reference to the given bool and assigns it to the OnlyPermission field.
func (o *PermissionSubjectPermissionRequestMetadata) SetOnlyPermission(v bool) {
	o.OnlyPermission = &v
}

// GetDepth returns the Depth field value if set, zero value otherwise.
func (o *PermissionSubjectPermissionRequestMetadata) GetDepth() int32 {
	if o == nil || IsNil(o.Depth) {
		var ret int32
		return ret
	}
	return *o.Depth
}

// GetDepthOk returns a tuple with the Depth field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PermissionSubjectPermissionRequestMetadata) GetDepthOk() (*int32, bool) {
	if o == nil || IsNil(o.Depth) {
		return nil, false
	}
	return o.Depth, true
}

// HasDepth returns a boolean if a field has been set.
func (o *PermissionSubjectPermissionRequestMetadata) HasDepth() bool {
	if o != nil && !IsNil(o.Depth) {
		return true
	}

	return false
}

// SetDepth gets a reference to the given int32 and assigns it to the Depth field.
func (o *PermissionSubjectPermissionRequestMetadata) SetDepth(v int32) {
	o.Depth = &v
}

func (o PermissionSubjectPermissionRequestMetadata) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PermissionSubjectPermissionRequestMetadata) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.SchemaVersion) {
		toSerialize["schema_version"] = o.SchemaVersion
	}
	if !IsNil(o.SnapToken) {
		toSerialize["snap_token"] = o.SnapToken
	}
	if !IsNil(o.OnlyPermission) {
		toSerialize["only_permission"] = o.OnlyPermission
	}
	if !IsNil(o.Depth) {
		toSerialize["depth"] = o.Depth
	}
	return toSerialize, nil
}

type NullablePermissionSubjectPermissionRequestMetadata struct {
	value *PermissionSubjectPermissionRequestMetadata
	isSet bool
}

func (v NullablePermissionSubjectPermissionRequestMetadata) Get() *PermissionSubjectPermissionRequestMetadata {
	return v.value
}

func (v *NullablePermissionSubjectPermissionRequestMetadata) Set(val *PermissionSubjectPermissionRequestMetadata) {
	v.value = val
	v.isSet = true
}

func (v NullablePermissionSubjectPermissionRequestMetadata) IsSet() bool {
	return v.isSet
}

func (v *NullablePermissionSubjectPermissionRequestMetadata) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePermissionSubjectPermissionRequestMetadata(val *PermissionSubjectPermissionRequestMetadata) *NullablePermissionSubjectPermissionRequestMetadata {
	return &NullablePermissionSubjectPermissionRequestMetadata{value: val, isSet: true}
}

func (v NullablePermissionSubjectPermissionRequestMetadata) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePermissionSubjectPermissionRequestMetadata) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


