/*
Permify API

Permify is an open source authorization service for creating fine-grained and scalable authorization systems.

API version: v0.10.1
Contact: hello@permify.co
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package permify

import (
	"encoding/json"
)

// checks if the PermissionExpandBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PermissionExpandBody{}

// PermissionExpandBody PermissionExpandRequest is the request message for the Expand method in the Permission service.
type PermissionExpandBody struct {
	Metadata *PermissionExpandRequestMetadata `json:"metadata,omitempty"`
	Entity *Entity `json:"entity,omitempty"`
	// Name of the permission to be expanded, not required, must start with a letter and can include alphanumeric and underscore, max 64 bytes.
	Permission *string `json:"permission,omitempty"`
	Context *Context `json:"context,omitempty"`
	// Additional arguments associated with this request.
	Arguments []Argument `json:"arguments,omitempty"`
}

// NewPermissionExpandBody instantiates a new PermissionExpandBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPermissionExpandBody() *PermissionExpandBody {
	this := PermissionExpandBody{}
	return &this
}

// NewPermissionExpandBodyWithDefaults instantiates a new PermissionExpandBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPermissionExpandBodyWithDefaults() *PermissionExpandBody {
	this := PermissionExpandBody{}
	return &this
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *PermissionExpandBody) GetMetadata() PermissionExpandRequestMetadata {
	if o == nil || IsNil(o.Metadata) {
		var ret PermissionExpandRequestMetadata
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PermissionExpandBody) GetMetadataOk() (*PermissionExpandRequestMetadata, bool) {
	if o == nil || IsNil(o.Metadata) {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *PermissionExpandBody) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given PermissionExpandRequestMetadata and assigns it to the Metadata field.
func (o *PermissionExpandBody) SetMetadata(v PermissionExpandRequestMetadata) {
	o.Metadata = &v
}

// GetEntity returns the Entity field value if set, zero value otherwise.
func (o *PermissionExpandBody) GetEntity() Entity {
	if o == nil || IsNil(o.Entity) {
		var ret Entity
		return ret
	}
	return *o.Entity
}

// GetEntityOk returns a tuple with the Entity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PermissionExpandBody) GetEntityOk() (*Entity, bool) {
	if o == nil || IsNil(o.Entity) {
		return nil, false
	}
	return o.Entity, true
}

// HasEntity returns a boolean if a field has been set.
func (o *PermissionExpandBody) HasEntity() bool {
	if o != nil && !IsNil(o.Entity) {
		return true
	}

	return false
}

// SetEntity gets a reference to the given Entity and assigns it to the Entity field.
func (o *PermissionExpandBody) SetEntity(v Entity) {
	o.Entity = &v
}

// GetPermission returns the Permission field value if set, zero value otherwise.
func (o *PermissionExpandBody) GetPermission() string {
	if o == nil || IsNil(o.Permission) {
		var ret string
		return ret
	}
	return *o.Permission
}

// GetPermissionOk returns a tuple with the Permission field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PermissionExpandBody) GetPermissionOk() (*string, bool) {
	if o == nil || IsNil(o.Permission) {
		return nil, false
	}
	return o.Permission, true
}

// HasPermission returns a boolean if a field has been set.
func (o *PermissionExpandBody) HasPermission() bool {
	if o != nil && !IsNil(o.Permission) {
		return true
	}

	return false
}

// SetPermission gets a reference to the given string and assigns it to the Permission field.
func (o *PermissionExpandBody) SetPermission(v string) {
	o.Permission = &v
}

// GetContext returns the Context field value if set, zero value otherwise.
func (o *PermissionExpandBody) GetContext() Context {
	if o == nil || IsNil(o.Context) {
		var ret Context
		return ret
	}
	return *o.Context
}

// GetContextOk returns a tuple with the Context field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PermissionExpandBody) GetContextOk() (*Context, bool) {
	if o == nil || IsNil(o.Context) {
		return nil, false
	}
	return o.Context, true
}

// HasContext returns a boolean if a field has been set.
func (o *PermissionExpandBody) HasContext() bool {
	if o != nil && !IsNil(o.Context) {
		return true
	}

	return false
}

// SetContext gets a reference to the given Context and assigns it to the Context field.
func (o *PermissionExpandBody) SetContext(v Context) {
	o.Context = &v
}

// GetArguments returns the Arguments field value if set, zero value otherwise.
func (o *PermissionExpandBody) GetArguments() []Argument {
	if o == nil || IsNil(o.Arguments) {
		var ret []Argument
		return ret
	}
	return o.Arguments
}

// GetArgumentsOk returns a tuple with the Arguments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PermissionExpandBody) GetArgumentsOk() ([]Argument, bool) {
	if o == nil || IsNil(o.Arguments) {
		return nil, false
	}
	return o.Arguments, true
}

// HasArguments returns a boolean if a field has been set.
func (o *PermissionExpandBody) HasArguments() bool {
	if o != nil && !IsNil(o.Arguments) {
		return true
	}

	return false
}

// SetArguments gets a reference to the given []Argument and assigns it to the Arguments field.
func (o *PermissionExpandBody) SetArguments(v []Argument) {
	o.Arguments = v
}

func (o PermissionExpandBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PermissionExpandBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	if !IsNil(o.Entity) {
		toSerialize["entity"] = o.Entity
	}
	if !IsNil(o.Permission) {
		toSerialize["permission"] = o.Permission
	}
	if !IsNil(o.Context) {
		toSerialize["context"] = o.Context
	}
	if !IsNil(o.Arguments) {
		toSerialize["arguments"] = o.Arguments
	}
	return toSerialize, nil
}

type NullablePermissionExpandBody struct {
	value *PermissionExpandBody
	isSet bool
}

func (v NullablePermissionExpandBody) Get() *PermissionExpandBody {
	return v.value
}

func (v *NullablePermissionExpandBody) Set(val *PermissionExpandBody) {
	v.value = val
	v.isSet = true
}

func (v NullablePermissionExpandBody) IsSet() bool {
	return v.isSet
}

func (v *NullablePermissionExpandBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePermissionExpandBody(val *PermissionExpandBody) *NullablePermissionExpandBody {
	return &NullablePermissionExpandBody{value: val, isSet: true}
}

func (v NullablePermissionExpandBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePermissionExpandBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


