/*
Permify API

Permify is an open source authorization service for creating fine-grained and scalable authorization systems.

API version: v0.10.1
Contact: hello@permify.co
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package permify

import (
	"encoding/json"
)

// checks if the DataChanges type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DataChanges{}

// DataChanges DataChanges represent changes in data with a snap token and a list of data change objects.
type DataChanges struct {
	// The snapshot token.
	SnapToken *string `json:"snap_token,omitempty"`
	// The list of data changes.
	DataChanges []DataChange `json:"data_changes,omitempty"`
}

// NewDataChanges instantiates a new DataChanges object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDataChanges() *DataChanges {
	this := DataChanges{}
	return &this
}

// NewDataChangesWithDefaults instantiates a new DataChanges object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDataChangesWithDefaults() *DataChanges {
	this := DataChanges{}
	return &this
}

// GetSnapToken returns the SnapToken field value if set, zero value otherwise.
func (o *DataChanges) GetSnapToken() string {
	if o == nil || IsNil(o.SnapToken) {
		var ret string
		return ret
	}
	return *o.SnapToken
}

// GetSnapTokenOk returns a tuple with the SnapToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DataChanges) GetSnapTokenOk() (*string, bool) {
	if o == nil || IsNil(o.SnapToken) {
		return nil, false
	}
	return o.SnapToken, true
}

// HasSnapToken returns a boolean if a field has been set.
func (o *DataChanges) HasSnapToken() bool {
	if o != nil && !IsNil(o.SnapToken) {
		return true
	}

	return false
}

// SetSnapToken gets a reference to the given string and assigns it to the SnapToken field.
func (o *DataChanges) SetSnapToken(v string) {
	o.SnapToken = &v
}

// GetDataChanges returns the DataChanges field value if set, zero value otherwise.
func (o *DataChanges) GetDataChanges() []DataChange {
	if o == nil || IsNil(o.DataChanges) {
		var ret []DataChange
		return ret
	}
	return o.DataChanges
}

// GetDataChangesOk returns a tuple with the DataChanges field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DataChanges) GetDataChangesOk() ([]DataChange, bool) {
	if o == nil || IsNil(o.DataChanges) {
		return nil, false
	}
	return o.DataChanges, true
}

// HasDataChanges returns a boolean if a field has been set.
func (o *DataChanges) HasDataChanges() bool {
	if o != nil && !IsNil(o.DataChanges) {
		return true
	}

	return false
}

// SetDataChanges gets a reference to the given []DataChange and assigns it to the DataChanges field.
func (o *DataChanges) SetDataChanges(v []DataChange) {
	o.DataChanges = v
}

func (o DataChanges) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DataChanges) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.SnapToken) {
		toSerialize["snap_token"] = o.SnapToken
	}
	if !IsNil(o.DataChanges) {
		toSerialize["data_changes"] = o.DataChanges
	}
	return toSerialize, nil
}

type NullableDataChanges struct {
	value *DataChanges
	isSet bool
}

func (v NullableDataChanges) Get() *DataChanges {
	return v.value
}

func (v *NullableDataChanges) Set(val *DataChanges) {
	v.value = val
	v.isSet = true
}

func (v NullableDataChanges) IsSet() bool {
	return v.isSet
}

func (v *NullableDataChanges) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDataChanges(val *DataChanges) *NullableDataChanges {
	return &NullableDataChanges{value: val, isSet: true}
}

func (v NullableDataChanges) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDataChanges) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


